const BLOG_CATEGORIES = [
    "Technology",
    "Health",
    "Travel",   
    "Food",
    "Lifestyle",
    "Education",    
    "Finance",
    "Entertainment",
    "Sports",
    "Science",
    "Art",
    "History",
    "Politics",
    "Environment",
    "Culture",
    "Business",
    "Fashion",
    "Music",
    "Books",
    "Movies",
    "Photography",
    "DIY",
    "Parenting",
    "Mental Health",
    "Productivity",
    "Self-Improvement",
    "Relationships",    
    "Spirituality",
    "Gaming",
    "Automotive",
    "Pets",
    "Gardening",
    "Home Improvement",
    "Crafts",
    "Social Issues",
    "Other"
]

export { BLOG_CATEGORIES };